# Generated by Django 4.1 on 2022-08-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_school_kyc_alter_school_email_alter_school_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
